# Generated by Django 6.0.3 on 2026-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_whatsappnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnotification',
            name='message_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappnotification',
            name='message_type',
            field=models.CharField(blank=True, default='text', max_length=50),
        ),
    ]
